config:
  mode: 'GCN'
  visible: False
  hidden_dim: 128
  max_epoch: 1000
  batch_size: 128
  no_up: 50
  lr: 0.0001
  weight_decay: 0.00001
  dropout: 0.3
  loss_func: "cross_entropy"
  optimizer: 'adam'